// src/components/oauth/Service.vue
<template>
  <v-layout align-center justify-center row fill-height>
  <v-card>
        <v-card-title>
            <span class="headline">Service Authorize</span>
        </v-card-title>
        <v-card-text>
          <h3>Authorize "{{getServiceName()}}" to use your account?</h3>
            <v-container grid-list-md>
            <v-layout wrap>
                <v-flex xs12>
                    <v-alert
                      :value="errorMessage"
                      type="error"
                    >
                      * Check your email or password.
                      * If the problem persists please contact the "{{getServiceName()}}" administrator.
                    </v-alert>
                </v-flex>
                <v-flex xs12>
                  <v-progress-linear :indeterminate="true" v-show="progress"></v-progress-linear>
                </v-flex>
                <v-flex xs12>
                    <v-text-field
                        v-model="email"
                        :rules="[rules.required, rules.email]"
                        label="E-mail"
                    ></v-text-field>
                </v-flex>
                <v-flex xs12>
                    <v-text-field
                        v-model="password"
                        :append-icon="show1 ? 'visibility_off' : 'visibility'"
                        :rules="[rules.required, rules.min]"
                        :type="show1 ? 'text' : 'password'"
                        name="input-10-1"
                        label="Password"
                        hint="At least 8 characters"
                        counter
                        @click:append="show1 = !show1"
                    ></v-text-field>
                </v-flex>
            </v-layout>
            </v-container>
        </v-card-text>
        <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn color="primary" flat @click.native="login()" :disabled="!validate()">Confilm</v-btn>
            <v-btn flat @click.native="cancel()">Cancel</v-btn>
        </v-card-actions>
    </v-card>
    </v-layout>
</template>
<script>
import AWS from "aws-sdk";
const decrypt = require("../../decrypt");

export default {
  data: () => ({
    title: null,
    e1: 1,
    email: "",
    password: "",
    errorMessage: null,
    show1: false,
    progress: false,
    rules: {
      required: value => !!value || "Required.",
      counter: value => value.length <= 20 || "Max 20 characters",
      min: v => v.length >= 8 || "Min 8 characters",
      email: value => {
        const pattern = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return pattern.test(value) || "Invalid e-mail.";
      }
    }
  }),
  mounted: function() {
    if(!this.getServiceToken()){
      this.$router.push({ path: "/" });
    }
  },
  methods: {
    getServiceName: function() {
      return this.$route.params.serviceName;
    },
    getServiceToken: function() {
      return decodeURIComponent(this.$route.params.serviceToken);
    },
    validate: function() {
      return (
        this.rules.required(this.email) == true &&
        this.rules.required(this.password) == true &&
        this.rules.min(this.password) == true &&
        this.rules.email(this.email) == true
      );
    },
    login: function() {
      const self = this;
      this.progress = true;
      this.errorMessage = null;
      let email = this.email;
      let psw = this.password;
      const ks = decrypt.get("auth_service").split(",");
      AWS.config.update({
        accessKeyId: ks[0],
        secretAccessKey: ks[1]
      });
      AWS.config.region = "us-east-1";
      let lambda = new AWS.Lambda();
      let params = {
        FunctionName: "auth_service",
        Payload: JSON.stringify({
          username: email,
          password: psw,
          serviceToken: this.getServiceToken(),
          serviceName: this.getServiceName()
        })
      };
      
      lambda.invoke(params, function(err, data) {
        self.progress = false;
        if (err) {
          self.errorMessage = JSON.stringify(err, undefined, 1);
          return;
        } else {
          let json = JSON.parse(data.Payload.toString());
          if (json.errorMessage) {
            self.errorMessage = JSON.stringify(json.errorMessage, undefined, 1);
            return;
          }

          let url = json.ReturnObj.Url;
          url += ("?userid=" + json.UserId);
          if(json.ReturnObj.QueryParams){
            url += "&";
            url += self.encodeQueryData(json.ReturnObj.QueryParams);
          }
          document.location = url;
        }
      });
    },
    cancel: function() {
      this.$router.push({ path: "/" });
    },
    encodeQueryData: function(data) {
      const ret = [];
      for (let d in data)
        ret.push(encodeURIComponent(d) + '=' + encodeURIComponent(data[d]));
      return ret.join('&');
    }
  }
};
</script>

// src/pages/oauth/service.tsx
import {
    Box,
    Button,
    Flex,
    FormControl,
    Input,
    InputGroup,
    InputLeftElement,
    InputRightElement,
    Stack,
    useBoolean,
    Container,
    Heading,
    Image,
    FormErrorMessage,
} from '@chakra-ui/react'
import { DefaultLayout } from '~/layout/Default'
import { Helmet } from 'react-helmet-async'
import { FaLock } from 'react-icons/fa'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { getAccessKeyAndSecret } from '~/util/decrypt'
import AWS from 'aws-sdk'
import React from 'react'
import { MdAlternateEmail } from 'react-icons/md'

export default () => {
    const urlParams = useParams<{ serviceName: string; serviceToken: string }>()
    const [showPassword, setShowPassword] = useBoolean()
    const [isLoading, setLoading] = useBoolean()
    const [email, setEmail] = useState<string>()
    const [password, setPassword] = useState<string>()
    const [errorMessage, setErrorMessage] = useState('')
    const navigate = useNavigate()

    const changeEmail = (e: React.ChangeEvent<HTMLInputElement>) => {
        setEmail(e.target.value)
    }
    const changePassword = (e: React.ChangeEvent<HTMLInputElement>) => {
        setPassword(e.target.value)
    }

    const encodeQueryData = (data: any) => {
        const ret = []
        for (let d in data) ret.push(encodeURIComponent(d) + '=' + encodeURIComponent(data[d]))
        return ret.join('&')
    }

    const login = () => {
        setLoading.toggle()
        let errorMsg = ''
        !(async () => {
            try {
                const ks = getAccessKeyAndSecret('auth_service').split(',')
                AWS.config.update({
                    accessKeyId: ks[0],
                    secretAccessKey: ks[1],
                })

                const lambda = new AWS.Lambda()
                const params = {
                    FunctionName: 'auth_service',
                    Payload: JSON.stringify({
                        username: email,
                        password: password,
                        serviceToken: urlParams.serviceToken,
                        serviceName: urlParams.serviceName,
                    }),
                }
                const data = await lambda.invoke(params).promise()
                const json = JSON.parse(data.Payload?.toString() ?? '')
                if (json.errorMessage) {
                    errorMsg = JSON.stringify(json.errorMessage, undefined, 1)
                    return
                } else {
                    let url = json.ReturnObj.Url
                    url += '?userid=' + json.UserId
                    if (json.ReturnObj.QueryParams) {
                        url += '&'
                        url += encodeQueryData(json.ReturnObj.QueryParams)
                    }
                    window.location.href = url
                }
            } catch (e) {
                console.log(JSON.stringify(e, undefined, 1))
            } finally {
                setErrorMessage(errorMsg)
                setLoading.toggle()
            }
        })()
    }

    const [errors, setErrors] = useState({ email: '', password: '' })
    useEffect(() => {
        const newState = { email: '', password: '' }
        if (email !== undefined && !email) {
            newState.email = 'email is required.'
        }

        if (password !== undefined && !password) {
            newState.password = 'password is required.'
        } else if (password !== undefined && password.length < 8) {
            newState.password = 'password must be at least 8 characters.'
        }

        setErrors(newState)
    }, [email, password])

    const valid = useMemo(() => {
        return !errors.email && !errors.password && email && password
    }, [errors, email, password])

    const cancel = () => {
        navigate('/')
    }

    return (
        <DefaultLayout>
            <Helmet>
                <title>Service Authorizer</title>
            </Helmet>
            <Flex mt={4} flexDirection="column" justifyContent="center" alignItems="center">
                <Stack flexDir="column" mb="2" justifyContent="center" alignItems="center">
                    <Box minW={{ base: '90%', md: '468px' }}>
                        <form>
                            <Stack spacing={4} p="1rem" backgroundColor="whiteAlpha.900" boxShadow="md">
                                <Flex alignItems={'center'} flexDirection={'column'} m={4}>
                                    <Image boxSize={'40%'} objectFit={'cover'} src={'/icons/icon-512x512.png'}></Image>
                                    <Heading size={'md'} textAlign={'center'}>
                                        Authorize {urlParams.serviceName} to use your account?
                                    </Heading>
                                </Flex>
                                {!!errorMessage && (
                                    <Container color={'red.500'} borderWidth="1px" borderRadius="lg">
                                        {errorMessage}
                                    </Container>
                                )}
                                <FormControl isInvalid={!!errors.email}>
                                    <InputGroup>
                                        <InputLeftElement pointerEvents="none" children={<MdAlternateEmail color="#CBD5E0" />} />
                                        <Input
                                            isRequired
                                            name="email"
                                            type="email"
                                            placeholder="email address"
                                            onChange={changeEmail}
                                            value={email}
                                        />
                                    </InputGroup>
                                    <FormErrorMessage>{errors.email}</FormErrorMessage>
                                </FormControl>
                                <FormControl isInvalid={!!errors.password}>
                                    <InputGroup>
                                        <InputLeftElement
                                            pointerEvents="none"
                                            color="gray.300"
                                            children={<FaLock color="#CBD5E0" />}
                                        />
                                        <Input
                                            name="password"
                                            type={showPassword ? 'text' : 'password'}
                                            placeholder="password"
                                            onChange={changePassword}
                                            value={password}
                                        />
                                        <InputRightElement width="4.5rem">
                                            <Button h="1.75rem" size="sm" onClick={setShowPassword.toggle}>
                                                {showPassword ? 'Hide' : 'Show'}
                                            </Button>
                                        </InputRightElement>
                                    </InputGroup>
                                    <FormErrorMessage>{errors.password}</FormErrorMessage>
                                </FormControl>
                                <Button
                                    disabled={!valid}
                                    isLoading={isLoading}
                                    borderRadius={0}
                                    variant="solid"
                                    colorScheme="teal"
                                    width="full"
                                    onClick={() => login()}>
                                    Confirm
                                </Button>
                                <Button
                                    isLoading={isLoading}
                                    borderRadius={0}
                                    variant="solid"
                                    width="full"
                                    onClick={() => cancel()}>
                                    Cancel
                                </Button>
                            </Stack>
                        </form>
                    </Box>
                </Stack>
            </Flex>
        </DefaultLayout>
    )
}
