// src/components/Privacy.vue
<template>
  <v-container fluid>
        <div>
            <h1>プライバシーポリシー</h1>
            </div>
            <div>
            <p>MinIRは、BMSプレイヤー（ユーザー）にIRサービスを提供します。サービス提供に当たり、個人情報の有用性を鑑みて、個人の権利と利益を保護する情報保護の方針を確立し、この方針を実行します。</p>
            <p>この方針の中で使う「個人情報」という用語は、電子メールアドレス、オンライン識別子等の識別子を用いて、ユーザーを直接間接を問わず特定できる情報を意味します。</p>
            <p>EUの一般データ保護規則2016 (『GDPR』と呼びます)上は、MinIR管理者は、個人情報のコントローラーに当たり、MinIRのウェブサイトの責任者です。</p>
            <h2>MinIRのデータ守秘に関する方針</h2>
            <ol>
                <li>
                <span>MinIRは、サービス内容と規模に応じて、然るべき個人情報を取得し、使用し、提供します。</span>
                </li>
                <li>
                <span>MinIRは、個人情報の使用目的を特定し、個人情報の使用がその目的を逸脱しないことを確実とします。</span>
                </li>
                <li>
                <span>MinIRは、個人情報の使用に関する法律、政府が設定した方針、およびその他の関連政令を遵守します。</span>
                </li>
            </ol>
            <h2>MinIRが収集する情報とは?</h2>
            <p>収取する個人情報およびユーザーに関する個人情報の収集方法は、以下の通りです。</p>
            <ul>
                <li>
                <b>ユーザーがMinIRに提供する個人情報</b>
                <span> ユーザーが、書式に記入することにより、電子メールアドレスを含む個人情報を提供することがあります。これには、MinIR使用するための登録をする際や、MinIRを利用する際にユーザーが提供する個人情報が含まれます。</span>
                </li>
                <li>
                <b>MinIRが収集する個人情報</b>
                <span> ユーザーがMinIRを利用する際に、ユーザーの装置、ブラウジング行為とパターン、MinIRへのアクセス日、MinIRの閲覧前にユーザーが閲覧したウェブサイト、ユーザーのブラウザ、OS、IPアドレス、およびドメインネームに関する技術情報が自動的に収集されます。これらの個人情報は、クッキーや、サーバーログや、その他類似の技術を使って収集されます。ただし、アクセスログに記録されているコンテンツは、個人情報と紐づけては使用されません。
                    MinIRとサービスの向上を助けるサーバー運営情報として使用されます。
                </span>
                </li>
            </ul>
            <p>ユーザーは、ブラウザの設定により、クッキーの機能を無効にすることができますが、その結果ウェブサイト上のサービスの全部または一部が利用できなくなくなります。</p>
            <h2>クッキーに関して</h2>
            <p>他の多くのウェブサイトと同様、MinIRにおいても、「クッキー」を使用しています。</p>
            <p>クッキーとは、ウェブサーバーとユーザーのウェブブラウザとの間を転送され、ユーザーのコンピューターディスクや携帯電話デバイスにファイルとして保管される小さなデータです。</p>
            <p>MinIRは、クッキーを主として以下の目的に使用します。</p>
            <ul>
                <li>
                <span >ユーザーがMinIRを利用する際に、毎回パスワードを入力しないで済みます。</span>
                </li>
                <li >
                <span >MinIRのサービスを利用するユーザーの活動を理解する一助としての分析作業。</span>
                </li>
            </ul>
            <p>ユーザーは、ブラウザの設定を選択してクッキーの機能を不能にすることができます。ただし、その場合は、MinIRの全てのあるいは一部のサービスを使用できなくなることに留意ください。</p>
            <h2>MinIRの情報プロセシングの目的とは?</h2>
            <p>MinIRは、ユーザーの個人情報を下記の目的のために使用します。</p>
            <ul>
                <li >
                <span >ユーザーの特定</span>
                </li>
                <li >
                <span >MinIRの情報、システム、およびネットワークのモニタリングと保護 </span>
                </li>
                <li >
                <span >MinIRシステムの向上</span>
                </li>
            </ul>
            <h2>誰に情報を提供するのか?</h2>
            <p>ユーザーの個人情報は、厳に秘密扱いとします。この個人情報の保護に関する方針に規定する目的のため、下記の者にユーザーの個人情報を提供することができます。</p>
            <ul>
                <li >
                <span >データ保存、メンテナンスサービス、データベース管理、ウェブ分析、といった、MinIRのサービスを補助するサービスを提供する会社</span>
                </li>
                <li >
                <span >MinIRが、サービスを移転するために選んだ第三者。もしMinIRの運営者に何らかの変更が起こる場合は、新しい運営者がユーザーの個人情報を、この個人情報の保護に関する方針の規定と同じ方法で使用することになります。</span>
                </li>
            </ul>
            <p>すべての第三者に対し、ユーザーの個人情報の安全に配慮し、法律に則って取り扱うよう義務付けます。</p>
            <p>MinIRは、日本を拠点とするサービスです。 また、クラウドプロバイダー、Webホスティングなど、さまざまな国のサードパーティのサービスプロバイダーと連携しています。 ユーザーの情報はサービスの一環として、欧州経済地域（EEA）外に移転され、他の国（日本、および米国を含む）で保管または処理されます。
                MinIRを使用することにより、ユーザーは、自身の情報がこれらの場所に転送されることに同意したことになります。
            </p>
            <h2>情報の保存期間はどれくらいか?</h2>
            <p>MinIRは、ユーザーを特定できるような形式で、個人情報がプロセシングされる目的のために必要な期間を超えない間は、個人情報を保管します。 MinIRは、サービスを実行するために必要な限りで、ユーザーの個人情報を使用します。</p>
            <h2>ヨーロッパにおける守秘とされる権利</h2>
            <p>
                <b>ヨーロッパ在住者のみ該当</b>
                <span > MinIRは、GDPRを含むデータ保護法上、プロセシングの法的根拠がある場合に限り、ユーザーの個人情報を収集しプロセシングします。法的根拠は、MinIRがユーザーの個人情報をプロセシングする目的によります。MinIRは、ユーザーの個人情報を以下の場合に限り収集し使用します。</span>
            </p>
            <ul>
                <li >
                <span >MinIRのサービスの提供に必要な場合</span>
                </li>
                <li >
                <span >調査と開発に必要な場合</span>
                </li>
                <li >
                <span >ユーザーが特定の目的のために収集使用に同意した場合</span>
                </li>
                <li >
                <span >法律上の義務を遵守するためにユーザーの個人情報をプロセシングする必要がある場合</span>
                </li>
            </ul>
            <p>ユーザーが特定の目的のために個人情報を使用することに同意した場合でも、ユーザーには、いつでも考えを変える権利があります。</p>
            <p>一定の状況において、ユーザーは、自己の個人情報に関してGDPR上の権利を有します。</p>
            <ul>
                <li >
                <b>個人情報へのアクセス要求</b>
                <span > ユーザーには、MinIRが保有している個人情報と個人情報をプロセシングする目的、または関連情報へのアクセスを要求する権利がある場合があります。
                </span>
                </li>
                <li >
                <b>個人情報の修正要求</b>
                <span > ユーザーには、MinIRが保有するユーザーの個人情報の不正確部分を訂正させる権利がある場合があります。</span>
                </li>
                <li >
                <b>個人情報の消去要求</b>
                <span > ユーザーには、ユーザーの個人情報の消去を要求する権利がある場合があります。</span>
                </li>
                <li >
                <b>個人情報のプロセシングの制限要求</b>
                <span > ユーザーには、ユーザーの個人情報のプロセシングを禁止もしくは制限する権利がある場合があります。</span>
                </li>
            </ul>
            <h2>連絡先</h2>
            <p>MinIRのこの個人情報の保護に関する方針またはその実行に関して質問がある場合は、Discord 海岸砂丘(Sack Magiclight)#6651 までご連絡ください。</p>
            <h2>本方針の変更</h2>
            <p>MinIRの情報管理の変更により本方針を改訂することがあります。重要な改訂がある場合は、改訂が有効となる前に、MinIRサイト上に通知を出して連絡します。個人情報保護に関する最新の情報については、このページを定期的に閲覧するようお願い致します。</p>
        </div>
  </v-container>
</template>

// src/pages/privacy.tsx
import { Box } from '@chakra-ui/react'
import { DefaultLayout } from '~/layout/Default'
import ChakraUIRenderer from 'chakra-ui-markdown-renderer'
import ReactMarkdown from 'react-markdown'
import { Helmet } from 'react-helmet-async'

export default () => {
    const m = `
MinIRは、BMSプレイヤー（ユーザー）にIRサービスを提供します。サービス提供に当たり、個人情報の有用性を鑑みて、個人の権利と利益を保護する情報保護の方針を確立し、この方針を実行します。

この方針の中で使う「個人情報」という用語は、電子メールアドレス、オンライン識別子等の識別子を用いて、ユーザーを直接間接を問わず特定できる情報を意味します。

EUの一般データ保護規則2016
(『GDPR』と呼びます)上は、MinIR管理者は、個人情報のコントローラーに当たり、MinIRのウェブサイトの責任者です。

MinIRのデータ守秘に関する方針
-----------------

1.  MinIRは、サービス内容と規模に応じて、然るべき個人情報を取得し、使用し、提供します。
2.  MinIRは、個人情報の使用目的を特定し、個人情報の使用がその目的を逸脱しないことを確実とします。
3.  MinIRは、個人情報の使用に関する法律、政府が設定した方針、およびその他の関連政令を遵守します。

MinIRが収集する情報とは?
---------------

収取する個人情報およびユーザーに関する個人情報の収集方法は、以下の通りです。

* **ユーザーがMinIRに提供する個人情報**
                            ユーザーが、書式に記入することにより、電子メールアドレスを含む個人情報を提供することがあります。これには、MinIR使用するための登録をする際や、MinIRを利用する際にユーザーが提供する個人情報が含まれます。
* **MinIRが収集する個人情報**
                            ユーザーがMinIRを利用する際に、ユーザーの装置、ブラウジング行為とパターン、MinIRへのアクセス日、MinIRの閲覧前にユーザーが閲覧したウェブサイト、ユーザーのブラウザ、OS、IPアドレス、およびドメインネームに関する技術情報が自動的に収集されます。これらの個人情報は、クッキーや、サーバーログや、その他類似の技術を使って収集されます。ただし、アクセスログに記録されているコンテンツは、個人情報と紐づけては使用されません。
                MinIRとサービスの向上を助けるサーバー運営情報として使用されます。
                

ユーザーは、ブラウザの設定により、クッキーの機能を無効にすることができますが、その結果ウェブサイト上のサービスの全部または一部が利用できなくなくなります。

クッキーに関して
--------

他の多くのウェブサイトと同様、MinIRにおいても、「クッキー」を使用しています。

クッキーとは、ウェブサーバーとユーザーのウェブブラウザとの間を転送され、ユーザーのコンピューターディスクや携帯電話デバイスにファイルとして保管される小さなデータです。

MinIRは、クッキーを主として以下の目的に使用します。

* ユーザーがMinIRを利用する際に、毎回パスワードを入力しないで済みます。
* MinIRのサービスを利用するユーザーの活動を理解する一助としての分析作業。

ユーザーは、ブラウザの設定を選択してクッキーの機能を不能にすることができます。ただし、その場合は、MinIRの全てのあるいは一部のサービスを使用できなくなることに留意ください。

MinIRの情報プロセシングの目的とは?
--------------------

MinIRは、ユーザーの個人情報を下記の目的のために使用します。

* ユーザーの特定
* MinIRの情報、システム、およびネットワークのモニタリングと保護
                
* MinIRシステムの向上

誰に情報を提供するのか?
------------

ユーザーの個人情報は、厳に秘密扱いとします。この個人情報の保護に関する方針に規定する目的のため、下記の者にユーザーの個人情報を提供することができます。

* データ保存、メンテナンスサービス、データベース管理、ウェブ分析、といった、MinIRのサービスを補助するサービスを提供する会社
* MinIRが、サービスを移転するために選んだ第三者。もしMinIRの運営者に何らかの変更が起こる場合は、新しい運営者がユーザーの個人情報を、この個人情報の保護に関する方針の規定と同じ方法で使用することになります。

すべての第三者に対し、ユーザーの個人情報の安全に配慮し、法律に則って取り扱うよう義務付けます。

MinIRは、日本を拠点とするサービスです。
また、クラウドプロバイダー、Webホスティングなど、さまざまな国のサードパーティのサービスプロバイダーと連携しています。
ユーザーの情報はサービスの一環として、欧州経済地域（EEA）外に移転され、他の国（日本、および米国を含む）で保管または処理されます。
MinIRを使用することにより、ユーザーは、自身の情報がこれらの場所に転送されることに同意したことになります。

情報の保存期間はどれくらいか?
---------------

MinIRは、ユーザーを特定できるような形式で、個人情報がプロセシングされる目的のために必要な期間を超えない間は、個人情報を保管します。
MinIRは、サービスを実行するために必要な限りで、ユーザーの個人情報を使用します。

ヨーロッパにおける守秘とされる権利
-----------------

**ヨーロッパ在住者のみ該当**
            MinIRは、GDPRを含むデータ保護法上、プロセシングの法的根拠がある場合に限り、ユーザーの個人情報を収集しプロセシングします。法的根拠は、MinIRがユーザーの個人情報をプロセシングする目的によります。MinIRは、ユーザーの個人情報を以下の場合に限り収集し使用します。

* MinIRのサービスの提供に必要な場合
* 調査と開発に必要な場合
* ユーザーが特定の目的のために収集使用に同意した場合
* 法律上の義務を遵守するためにユーザーの個人情報をプロセシングする必要がある場合

ユーザーが特定の目的のために個人情報を使用することに同意した場合でも、ユーザーには、いつでも考えを変える権利があります。

一定の状況において、ユーザーは、自己の個人情報に関してGDPR上の権利を有します。

* **個人情報へのアクセス要求**
                            ユーザーには、MinIRが保有している個人情報と個人情報をプロセシングする目的、または関連情報へのアクセスを要求する権利がある場合があります。
                
* **個人情報の修正要求**
                            ユーザーには、MinIRが保有するユーザーの個人情報の不正確部分を訂正させる権利がある場合があります。
* **個人情報の消去要求**
                            ユーザーには、ユーザーの個人情報の消去を要求する権利がある場合があります。
* **個人情報のプロセシングの制限要求**
                            ユーザーには、ユーザーの個人情報のプロセシングを禁止もしくは制限する権利がある場合があります。

連絡先
---

MinIRのこの個人情報の保護に関する方針またはその実行に関して質問がある場合は、Discord
海岸砂丘(Sack Magiclight)#6651 までご連絡ください。

本方針の変更
------

MinIRの情報管理の変更により本方針を改訂することがあります。重要な改訂がある場合は、改訂が有効となる前に、MinIRサイト上に通知を出して連絡します。個人情報保護に関する最新の情報については、このページを定期的に閲覧するようお願い致します。

    `
    return (
        <DefaultLayout>
            <Helmet>
                <title>Privacy Policy</title>
            </Helmet>
            <Box padding={10}>
                <ReactMarkdown components={ChakraUIRenderer()} skipHtml>
                    {m}
                </ReactMarkdown>
            </Box>
        </DefaultLayout>
    )
}
