// src/components/Song.vue
<template>
  <div>
    <v-container>
      <v-layout row wrap>
        <v-flex xs12 md6>
          <v-container grid-list-md text-xs-center>
            <v-layout row wrap>
              <v-flex xs12>
                <v-card>
                  <v-container
                    fluid
                    grid-list-lg
                  >
                    <v-layout row wrap>
                        <v-flex xs12 mb-2>
                          <v-card flat>
                            <v-layout>
                              <v-flex xs2>
                                <v-icon>music_note</v-icon>
                              </v-flex>
                              <v-flex xs10>
                                <div style="overflow-wrap: anywhere;">{{ songData.genre }}</div>
                              </v-flex>
                            </v-layout>
                          </v-card>
                        </v-flex>
                        <v-flex xs12 mb-2>
                          <v-card flat>
                            <v-layout>
                              <v-flex xs2>
                                <v-icon>title</v-icon>
                              </v-flex>
                              <v-flex xs10>
                                <div style="overflow-wrap: anywhere;">{{ songData.title }}</div>
                              </v-flex>
                            </v-layout>
                          </v-card>
                        </v-flex>
                        <v-flex xs12 mb-2>
                          <v-card flat>
                            <v-layout>
                              <v-flex xs2>
                                <v-icon>person</v-icon>
                              </v-flex>
                              <v-flex xs10>
                                <div style="overflow-wrap: anywhere;">{{ songData.artist }}</div>
                              </v-flex>
                            </v-layout>
                          </v-card>
                        </v-flex>
                        <v-flex xs12 mb-2>
                          <v-card flat>
                            <v-layout>
                              <v-flex xs2>
                                <v-icon>fast_forward</v-icon>
                              </v-flex>
                              <v-flex xs10>
                                {{ songData.maxbpm == songData.minbpm ? songData.maxbpm : songData.minbpm + "-" + songData.maxbpm }}
                              </v-flex>
                            </v-layout>
                          </v-card>
                        </v-flex>
                        <v-flex xs12 mb-2>
                          <v-card flat>
                            <v-layout>
                              <v-flex xs2>
                                <v-icon>stars</v-icon>
                              </v-flex>
                              <v-flex xs10>
                                ☆{{ songData.level }}
                              </v-flex>
                            </v-layout>
                          </v-card>
                        </v-flex>
                        <v-flex xs12 mb-2>
                          <v-card flat>
                            <v-layout>
                              <v-flex xs2>
                                <v-icon>assessment</v-icon>
                              </v-flex>
                              <v-flex xs10>
                                {{ songData.notes }} Notes&nbsp;/&nbsp;{{ songData.total }}&nbsp;total
                              </v-flex>
                            </v-layout>
                          </v-card>
                        </v-flex>
                        <v-flex xs12 mb-2 mt--2>
                          <v-card flat>
                            <v-layout>
                              <v-flex xs2 d-flex justify-center>
                                <v-icon>pin</v-icon>
                              </v-flex>
                              <v-flex xs10>
                                <v-text-field
                                  v-model="$route.params.songhash"
                                  readonly
                                  dense
                                  hide-details
                                  height="24px"
                                  style="padding-top: 0; margin-top: 0;"
                                >
                                  <template v-slot:append>
                                    <div style="margin-top: -4px;">
                                      <button
                                        v-clipboard:copy="$route.params.songhash"
                                      >
                                        <v-icon dense>content_paste</v-icon>
                                      </button>
                                    </div>
                                  </template>
                                </v-text-field>
                              </v-flex>
                            </v-layout>
                          </v-card>
                        </v-flex>
                        <v-flex xs12 mb-2 v-if="!progress">
                          <v-card flat>
                            <v-layout justify-start row>
                              <v-flex xs12 v-if="stellaPath">
                                <v-layout>
                                  <v-btn
                                    block
                                    color="#001529" 
                                    :href="stellaPath" target="_blank">
                                      <span style="color: white; text-transform: none;" >Stella / Satellite</span>
                                  </v-btn>
                                </v-layout>
                              </v-flex>
                              <v-flex xs12>
                                <v-layout>
                                  <v-btn
                                    block
                                    color="#FF7066" 
                                    :href="getCinnamonURL" target="_blank">
                                      <span style="color: white; text-transform: none;" >Cinnamon</span>
                                  </v-btn>
                                </v-layout>
                              </v-flex>
                              <v-flex xs12>
                                <v-layout>
                                  <v-btn
                                    block
                                    color="#75491E" 
                                    :href="getMochaURL" target="_blank">
                                      <span style="color: white; text-transform: none;" >Mocha</span>
                                  </v-btn>
                                </v-layout>
                              </v-flex>
                            </v-layout>
                          </v-card>
                        </v-flex>
                        <v-flex xs12 mb-2>
                          <v-card flat>
                            <v-layout justify-start row>
                              <v-flex xs12>
                                <social-sharing :url="getHref"
                                          :title="`[MinIR SongPage] ${songData.title}`"
                                          inline-template>
                                  <v-layout>
                                    <network network="twitter">
                                      <v-btn block color="#1b95e0">
                                        <v-icon color="white">fab fa-twitter</v-icon>
                                        <span style="color: white; text-transform: none;" >tweet</span>
                                      </v-btn>
                                    </network>
                                  </v-layout>
                                </social-sharing>
                              </v-flex>
                            </v-layout>
                          </v-card>
                        </v-flex>
                      </v-layout>
                  </v-container>
                </v-card>
              </v-flex>
            </v-layout>
          </v-container>
        </v-flex>
        <v-flex xs12 md6>
          <v-container grid-list-md text-xs-center>
            <v-layout row wrap>
              <v-flex xs12 v-if="videoId" v-show="!$vuetify.breakpoint.xs">
                <youtube :video-id="videoId" player-width="560" player-height="345"></youtube>
                <v-card v-if="signedIn">
                  <v-card-text>
                    <v-layout row>
                      <v-flex p>
                        <v-switch
                          v-model="enableVideoIdEditor"
                          color="primary"
                        ></v-switch>
                      </v-flex>
                      <v-flex xs12>
                        <v-text-field
                          :disabled="!enableVideoIdEditor"
                          v-model="videoId"
                        ></v-text-field>
                      </v-flex>
                      <v-flex p>
                        <v-btn 
                          :loading="updateVideoIdLoading"
                          :disabled="!enableVideoIdEditor || updateVideoIdLoading"
                          color="primary" 
                          @click.native="updateVideoId()">Update Video ID</v-btn>
                      </v-flex>
                    </v-layout>
                  </v-card-text>
                </v-card>
              </v-flex>
              <v-flex xs12 v-if="!videoId" v-show="!$vuetify.breakpoint.xs">
                <v-layout justify-center column fill-height>
                  <v-card>
                    <v-card-title primary-title>
                      <div>
                        <h3 class="headline mb-0">Nothing Video</h3>
                        <div>Please add Youtube video.<span v-if="!signedIn">(Need to login.)</span></div>
                      </div>
                    </v-card-title>
                    <v-card-text v-if="signedIn">
                      <v-layout row>
                        <v-flex p>
                          <v-switch
                            v-model="enableVideoIdEditor"
                            color="primary"
                          ></v-switch>
                        </v-flex>
                        <v-flex xs12>
                          <v-text-field
                            :disabled="!enableVideoIdEditor"
                            v-model="videoId"
                          ></v-text-field>
                        </v-flex>
                        <v-flex p>
                          <v-btn 
                            :loading="updateVideoIdLoading"
                            :disabled="!enableVideoIdEditor ||updateVideoIdLoading"
                            color="primary" 
                            @click.native="updateVideoId()">Update Video ID</v-btn>
                        </v-flex>
                      </v-layout>
                    </v-card-text>
                  </v-card>
                </v-layout>
              </v-flex>
            </v-layout>
          </v-container>
        </v-flex>
      </v-layout>
    </v-container>
    <v-container text-xs-center>
      <v-layout row wrap>
        <v-flex xs12>
          <v-dialog v-model="progress" persistent max-width="290">
            <v-card>
              <v-card-text>
                <v-progress-linear indeterminate></v-progress-linear>
              </v-card-text>
            </v-card>
          </v-dialog>
          <div ref="table"></div>
        </v-flex>
      </v-layout>
    </v-container>
  </div>
</template>

<script>
/* eslint-disable */
import AWS from "aws-sdk";
import axios from "axios";
import Tabulator from "tabulator-tables";
import { AmplifyEventBus } from 'aws-amplify-vue';
import Amplify, { Auth } from 'aws-amplify';
const decrypt = require("../decrypt");

export default {
  name: "Song",
  watch: {
    $route(to, from) {
      this.getSongData();
    },
    signedIn: async function(newValue, oldValue) {
      this.signedIn = newValue;
    },
    tableData:{
      handler: function (newData) {
        this.table.replaceData(newData);
      },
      deep: true,
    }
  },
  props: {
    signedIn: Boolean
  },
  mounted: function() {
    this.getSongData();
  },
  data() {
    return {
      table: null,
      tableData: [],
      progress: false,
      songData: {},
      stellaPath: null,
      videoId: "",
      enableVideoIdEditor: false,
      updateVideoIdLoading: false,
    };
  },
  computed: {
    getHref : function() {
      return location.href;
    },
    getMochaURL : function() {
      return `https://mocha-repository.info/song.php?sha256=${this.getSongHash()}&lnmode=${(Number(this.getLnMode())+1)}`;
    },
    getCinnamonURL : function() {
      return `https://cinnamon.link/charts/${this.getSongHash()}`;
    }
  },
  methods: {
    getCurrentUser: async function(){
      try{
        const data = await Auth.currentAuthenticatedUser();
        const returnData = {
            AccessToken: data.signInUserSession.accessToken.jwtToken,
            RefreshToken: data.signInUserSession.refreshToken.token,
            UserId: data.signInUserSession.idToken.payload.sub
        };
        // eslint-disable-next-line
        console.log(returnData);
        return returnData;
      } catch(err){
        // eslint-disable-next-line
        console.log(err);
        return {};
      }
    },
    getYoutubeId: function(songData) {
      this.videoId = songData.video ? songData.video.videoid : "";
    },
    getSongHash: function() {
      return this.$route.params.songhash;
    },
    getLnMode: function() {
      return this.$route.params.lnmode;
    },
    createTable: function(notes) {
      const self = this;
      this.table = new Tabulator(this.$refs.table, {
        layout: "fitColumns",
        pagination:"local",
        paginationSize: 30,
        rowFormatter: function(row) {
          if (row.getData().novalidate) {
            row.getElement().style.backgroundColor = "#A6A6DF";
          }
        },
        columns: [
          { formatter: "rownum", align: "center", width: 40, headerSort: false, resizable: false },
          {
            title: "Name",
            field: "username",
            resizable: false,
            minWidth: 150,
            headerSort: false,
            formatter: function(cell, formatterParams) {
              let data = cell.getRow().getData();
              let userid = data.userid;
              return `<a href="./#/viewer/user/${userid}">${cell.getValue()}</a>`;
            }
          },
          {
            title: "Score",
            field: "score",
            minWidth: 150,
            resizable: false,
            align: "left",
            formatter: "progress",
            formatterParams: { min: 0, max: notes * 2, legend: true },
            headerSort: false,
            cellClick: (e, cell) => {
              const data = cell.getRow().getData();
              self.$router.push(`/viewer/song/${self.getSongHash()}/${self.getLnMode()}/score/${data.userid}`)
            }
          },
          {
            title: "Combo",
            field: "combo",
            minWidth: 150,
            resizable: false,
            align: "left",
            formatter: "progress",
            formatterParams: {
              min: 0,
              max: notes,
              color: "orange",
              legend: true
            },
            headerSort: false
          },
          {
            title: "Clear",
            field: "clear",
            align: "center",
            width: 150,
            resizable: false,
            headerSort: false,
            formatter: function(cell, formatterParams) {
              switch (cell.getValue()) {
                case 0:
                  cell.getElement().style.backgroundColor =
                    "rgb(255, 255, 255)";
                  return "NoPlay";
                case 1:
                  cell.getElement().style.backgroundColor =
                    "rgb(192, 192, 192)";
                  return "Failed";
                case 2:
                  cell.getElement().style.backgroundColor =
                    "rgb(149, 149, 255)";
                  return "AssistEasy";
                case 3:
                  cell.getElement().style.backgroundColor =
                    "rgb(149, 149, 255)";
                  return "LightAssistEasy";
                case 4:
                  cell.getElement().style.backgroundColor =
                    "rgb(152, 251, 152)";
                  return "Easy";
                case 5:
                  cell.getElement().style.backgroundColor =
                    "rgb(152, 251, 152)";
                  return "Normal";
                case 6:
                  cell.getElement().style.backgroundColor = "rgb(255, 99, 71)";
                  return "Hard";
                case 7:
                  cell.getElement().style.backgroundColor = "rgb(255, 217, 0)";
                  return "ExHard";
                case 8:
                  cell.getElement().style.backgroundColor = "rgb(255, 140, 0)";
                  return "FullCombo";
                case 9:
                  cell.getElement().style.backgroundColor = "rgb(255, 140, 0)";
                  return "Perfect";
                case 10:
                  cell.getElement().style.backgroundColor = "rgb(255, 140, 0)";
                  return "Max";
              }
            }
          }
        ]
      });
    },
    getSongData: function() {
      this.progress = true;
      const songhash = this.getSongHash();
      const lnmode = this.getLnMode();

      const self = this;

      const ks = decrypt.get("get_song_data").split(",");
      AWS.config.update({
        accessKeyId: ks[0],
        secretAccessKey: ks[1]
      });
      AWS.config.region = "us-east-1";
      let lambda = new AWS.Lambda();
      let params = {
        FunctionName: "get_song_data",
        Payload: JSON.stringify({
          songhash: songhash + (lnmode ? "." + lnmode : ".0")
        })
      };

      lambda.invoke(params, function(err, data) {
        self.progress = false;
        if (!err) {
          const json = JSON.parse(data.Payload.toString());
          if (json.message == "success") {
            self.songData = json.SongData;
            self.createTable(json.SongData.notes);
            self.tableData = json.IRDatas;
            self.getYoutubeId(json.SongData);
            self.getStellaPath();
          }
        }
      });
    },
    updateVideoId: async function() {
      this.updateVideoIdLoading = true;
      let userData = await this.getCurrentUser();
      let Songhash = this.getSongHash();
      let VideoId = this.videoId;

      const ks = decrypt.get("update_song_data").split(",");
      AWS.config.update({
        accessKeyId: ks[0],
        secretAccessKey: ks[1]
      });
      AWS.config.region = "us-east-1";
      let lambda = new AWS.Lambda();
      let params = {
        FunctionName: "update_song_data",
        Payload: JSON.stringify({
          AccessToken: userData.AccessToken,
          RefreshToken: userData.RefreshToken,
          Songhash: Songhash,
          VideoId: VideoId,
        })
      };

      const self = this;
      try{
        const data = await lambda.invoke(params).promise();
        self.updateVideoIdLoading = false;
        self.enableVideoIdEditor = false;
        self.updateVideoIdLoading = false;
        self.getSongData();
      } catch (err){
        // error
      }
    },
    getStellaPath: function() {
      const self = this;
      axios.get(`https://stellabms.xyz/sha256/${this.getSongHash()}`,{
        headers: {
          'Content-Type': 'application/json;charset=UTF-8',
          'Access-Control-Allow-Origin': '*',
        }
      })
      .then((val) => {
        console.log(val);
        if(val.status != 404){
          self.stellaPath = `https://stellabms.xyz/sha256/${self.getSongHash()}`;
        } else {
          self.stellaPath = null;
        }
      }).catch((err) => {
        self.stellaPath = null;
      });
    }
  }
};
</script>

<style>
  @import '~tabulator-tables/dist/css/tabulator.min.css';
</style>

// src/pages/song.tsx
import {
    Box,
    Table,
    TableContainer,
    Tbody,
    Td,
    Tr,
    Progress,
    useDisclosure,
    Button,
    Input,
    IconButton,
    InputGroup,
    InputRightElement,
    useToast,
    ButtonGroup,
} from '@chakra-ui/react'
import { useNavigate, useParams } from 'react-router-dom'
import Lambda from 'aws-sdk/clients/lambda'
import { getAccessKeyAndSecret } from '~/util/decrypt'
import AWS from 'aws-sdk'
import { useEffect, useMemo, useState } from 'react'
import { DefaultLayout } from '~/layout/Default'

import { ReactTabulator } from 'react-tabulator'
import { Tabulator } from 'react-tabulator/lib/types/TabulatorTypes'
import 'react-tabulator/lib/styles.css'
import 'react-tabulator/lib/css/tabulator_semanticui.min.css'
import { CopyIcon } from '@chakra-ui/icons'
import { FaFacebook, FaLine, FaTwitter } from 'react-icons/fa'
import { useQuery } from 'react-query'
import axios from 'axios'
import { truncate } from 'lodash'
import { Helmet } from 'react-helmet-async'

type IRData = {
    clear: number
    combo: number
    datetime: string
    egr: number
    epg: number
    lgr: number
    lpg: number
    notes: number
    novalidate: boolean
    score: number
    songhash: string
    userid: string
    username: string
    type: string
}

type SongData = {
    artist: string
    bpm: number
    datetime: string
    genre: string
    judgerank: number
    level: string
    maxbpm: number
    minbpm: number
    mode: string
    notes: number
    songhash: string
    title: string
    total: number
    lnmode?: number
    video?: {
        videoid: string
        updateUserId: string
    }
}

export default () => {
    const navigate = useNavigate()
    const urlParams = useParams<{ songhash: string; lnmode: string }>()
    const [irData, setIRData] = useState<IRData[]>([])
    const [songData, setSongData] = useState<SongData>()
    const [isLoading, setLoading] = useState(false)
    const toast = useToast()

    const columns = useMemo<Tabulator.ColumnDefinition[]>(() => {
        return [
            {
                formatter: 'rownum',
                hozAlign: 'center',
                width: 80,
                headerSort: false,
                resizable: false,
                title: '',
                responsive: 0,
            },
            {
                title: 'Name',
                field: 'username',
                resizable: false,
                minWidth: 100,
                responsive: 0,
                headerSort: false,
                cellClick: (e: UIEvent, cell: Tabulator.CellComponent) => {
                    const data = cell.getRow().getData()
                    const userId = data.userid
                    navigate(`/viewer/user/${userId}`)
                },
                tooltip: 'go to user page.',
            },
            {
                title: 'Score',
                field: 'score',
                minWidth: 100,
                responsive: 0,
                resizable: false,
                hozAlign: 'left',
                formatter: 'progress',
                formatterParams: { min: 0, max: (songData?.notes ?? 0) * 2, legend: true },
                headerSort: false,
                cellClick: (e: any, cell: any) => {
                    const data = cell.getRow().getData()
                    navigate(`/viewer/song/${urlParams.songhash}/${urlParams.lnmode ?? '0'}/score/${data.userid}`)
                },
                tooltip: 'go to score page.',
            },
            {
                title: 'Combo',
                field: 'combo',
                minWidth: 150,
                responsive: 1,
                resizable: false,
                hozAlign: 'left',
                formatter: 'progress',
                formatterParams: {
                    min: 0,
                    max: songData?.notes ?? 0,
                    color: 'orange',
                    legend: true,
                },
                headerSort: false,
            },
            {
                title: 'Clear',
                field: 'clear',
                hozAlign: 'center',
                width: 100,
                responsive: 2,
                resizable: false,
                headerSort: false,
                formatter: (cell: Tabulator.CellComponent) => {
                    switch (cell.getValue()) {
                        case 0:
                            cell.getElement().style.backgroundColor = 'rgb(255, 255, 255)'
                            return 'NoPlay'
                        case 1:
                            cell.getElement().style.backgroundColor = 'rgb(192, 192, 192)'
                            return 'Failed'
                        case 2:
                            cell.getElement().style.backgroundColor = 'rgb(149, 149, 255)'
                            return 'AssistEasy'
                        case 3:
                            cell.getElement().style.backgroundColor = 'rgb(149, 149, 255)'
                            return 'LightAssistEasy'
                        case 4:
                            cell.getElement().style.backgroundColor = 'rgb(152, 251, 152)'
                            return 'Easy'
                        case 5:
                            cell.getElement().style.backgroundColor = 'rgb(152, 251, 152)'
                            return 'Normal'
                        case 6:
                            cell.getElement().style.backgroundColor = 'rgb(255, 99, 71)'
                            return 'Hard'
                        case 7:
                            cell.getElement().style.backgroundColor = 'rgb(255, 217, 0)'
                            return 'ExHard'
                        case 8:
                            cell.getElement().style.backgroundColor = 'rgb(255, 140, 0)'
                            return 'FullCombo'
                        case 9:
                            cell.getElement().style.backgroundColor = 'rgb(255, 140, 0)'
                            return 'Perfect'
                        case 10:
                            cell.getElement().style.backgroundColor = 'rgb(255, 140, 0)'
                            return 'Max'
                        default:
                            return ''
                    }
                },
            },
        ]
    }, [songData])

    const { data: stellaUrl, isLoading: isStellaLoading } = useQuery(
        'posts',
        async () => {
            const { data } = await axios.get(`https://stellabms.xyz/sha256/${urlParams.songhash}`, {
                headers: {
                    'Content-Type': 'application/json;charset=UTF-8',
                    'Access-Control-Allow-Origin': '*',
                },
            })
            return data
        },
        { retry: 0 },
    )

    useEffect(() => {
        setLoading(true)
        setIRData([])
        setSongData(undefined)
        getSongData()
    }, [urlParams.songhash, urlParams.lnmode])

    const getSongData = () => {
        const ks = getAccessKeyAndSecret('get_song_data').split(',')
        AWS.config.update({
            accessKeyId: ks[0],
            secretAccessKey: ks[1],
        })
        const lambda = new Lambda()
        const params = {
            FunctionName: 'get_song_data',
            Payload: JSON.stringify({
                songhash: (urlParams.songhash ?? '') + (urlParams.lnmode ? `.${urlParams.lnmode}` : '.0'),
            }),
        }

        lambda.invoke(params, function (err, data) {
            if (err) {
            } else {
                var json = JSON.parse(data.Payload?.toString() ?? '')
                if (json.message == 'success') {
                    setIRData(json.IRDatas)
                    setSongData(json.SongData)
                } else {
                }
            }
            setLoading(false)
        })
    }

    const rowFormatter = (row: Tabulator.RowComponent) => {
        if (row.getData().novalidate) {
            row.getElement().style.backgroundColor = '#A6A6DF'
        }
    }

    const handleCopy = (e: React.MouseEvent<HTMLButtonElement>) => {
        e.preventDefault()
        if (urlParams.songhash) {
            navigator.clipboard.writeText(urlParams.songhash)
            toast({
                description: 'Copied.',
                status: 'success',
                duration: 1500,
            })
        }
    }

    const openInNewTab = (url: string) => {
        const newWindow = window.open(url, '_blank', 'noopener,noreferrer')
        if (newWindow) newWindow.opener = null
    }

    const socialText = (title: string) => {
        return `[MinIR SongPage]%0D%0A${truncate(title, {
            length: 120,
        })}`
    }
    const socialUrl = (hash: string, lnmode?: string) => {
        return `https://www.gaftalk.com/minir/%23/viewer/song/${hash}${lnmode ? '/' + lnmode : ''}`
    }
    const socialTwitter = useMemo(() => {
        return () => {
            openInNewTab(
                `https://twitter.com/intent/tweet?text=${socialText(songData?.title ?? '')}%0D%0A${socialUrl(
                    urlParams.songhash ?? '',
                    urlParams.lnmode,
                )}`,
            )
        }
    }, [songData])
    const socialFacebook = useMemo(() => {
        return () => {
            openInNewTab(
                `https://www.facebook.com/sharer.php?quote=${socialText(songData?.title ?? '')}&u=${socialUrl(
                    urlParams.songhash ?? '',
                    urlParams.lnmode,
                )}`,
            )
        }
    }, [songData])

    const socialLine = useMemo(() => {
        return () => {
            openInNewTab(
                `https://social-plugins.line.me/lineit/share?text=${socialText(songData?.title ?? '')}&url=${socialUrl(
                    urlParams.songhash ?? '',
                    urlParams.lnmode,
                )}`,
            )
        }
    }, [songData])

    const routeLNModeUrl = (hash: string, lnmode: string) => {
        return `/viewer/song/${hash}/${lnmode}`
    }
    const routeLN = () => {
        navigate(routeLNModeUrl(urlParams.songhash ?? '', '0'))
    }
    const routeCN = () => {
        navigate(routeLNModeUrl(urlParams.songhash ?? '', '1'))
    }
    const routeHCN = () => {
        navigate(routeLNModeUrl(urlParams.songhash ?? '', '2'))
    }

    return (
        <DefaultLayout>
            <Helmet>
                <title>{songData?.title ?? 'MinIR'}</title>
            </Helmet>
            <Box padding={4}>
                {isLoading && <Progress size="xs" isIndeterminate />}
                <TableContainer>
                    <Table size="sm">
                        <Tbody>
                            <Tr>
                                <Td>SONG ID</Td>
                                <Td>
                                    <InputGroup size="sm">
                                        <Input value={urlParams.songhash} readOnly variant="flushed" pr="2.5rem" />
                                        <InputRightElement width="2.5rem">
                                            <IconButton
                                                aria-label="copy song id"
                                                icon={<CopyIcon />}
                                                size={'xs'}
                                                onClick={handleCopy}
                                            />
                                        </InputRightElement>
                                    </InputGroup>
                                </Td>
                            </Tr>
                            <Tr>
                                <Td>TITLE</Td>
                                <Td>{songData?.title}</Td>
                            </Tr>
                            <Tr>
                                <Td>ARTIST</Td>
                                <Td>{songData?.artist}</Td>
                            </Tr>
                            <Tr>
                                <Td>INFO</Td>
                                <Td>
                                    ☆{songData?.level} / {songData?.notes}notes / {songData?.total}total
                                </Td>
                            </Tr>
                            <Tr>
                                <Td>LINKS</Td>
                                <Td>
                                    <ButtonGroup variant="outline" spacing="2">
                                        {stellaUrl && (
                                            <Button color={'#001529'} size="xs" as={'a'} href={stellaUrl} target={'_blank'}>
                                                Stella / Satellite
                                            </Button>
                                        )}
                                        <Button
                                            color={'#FF7066'}
                                            size="xs"
                                            as={'a'}
                                            href={`https://cinnamon.link/charts/${urlParams.songhash}`}
                                            target={'_blank'}>
                                            Cinnamon
                                        </Button>
                                        <Button
                                            color={'#75491E'}
                                            size="xs"
                                            as={'a'}
                                            href={`https://mocha-repository.info/song.php?sha256=${urlParams.songhash}`}
                                            target={'_blank'}>
                                            Mocha-Repository
                                        </Button>
                                    </ButtonGroup>
                                </Td>
                            </Tr>
                            <Tr>
                                <Td>SOCIAL</Td>
                                <Td>
                                    <ButtonGroup variant="outline" spacing="2">
                                        <Button
                                            colorScheme="twitter"
                                            leftIcon={<FaTwitter />}
                                            size={'xs'}
                                            onClick={() => socialTwitter()}>
                                            Twitter
                                        </Button>
                                        <Button
                                            colorScheme="facebook"
                                            leftIcon={<FaFacebook />}
                                            size={'xs'}
                                            onClick={() => socialFacebook()}>
                                            Facebook
                                        </Button>
                                        <Button color="#06c755" leftIcon={<FaLine />} size={'xs'} onClick={() => socialLine()}>
                                            Line
                                        </Button>
                                    </ButtonGroup>
                                </Td>
                            </Tr>
                            <Tr>
                                <Td>LNMODE</Td>
                                <Td>
                                    <ButtonGroup size="xs" isAttached variant="outline">
                                        <Button
                                            mr={'-px'}
                                            colorScheme={'teal'}
                                            variant={!urlParams.lnmode || urlParams.lnmode === '0' ? 'solid' : 'outline'}
                                            onClick={() => routeLN()}>
                                            LN or #LNMODE
                                        </Button>
                                        <Button
                                            mr={'-px'}
                                            colorScheme={'teal'}
                                            variant={!songData?.lnmode && urlParams.lnmode === '1' ? 'solid' : 'outline'}
                                            onClick={() => routeCN()}>
                                            CN
                                        </Button>
                                        <Button
                                            colorScheme={'teal'}
                                            variant={!songData?.lnmode && urlParams.lnmode === '2' ? 'solid' : 'outline'}
                                            onClick={() => routeHCN()}>
                                            HCN
                                        </Button>
                                    </ButtonGroup>
                                </Td>
                            </Tr>
                        </Tbody>
                    </Table>
                </TableContainer>
                <ReactTabulator
                    className={'compact'}
                    data={irData}
                    columns={columns}
                    options={{
                        responsiveLayout: true,
                        pagination: 'local',
                        paginationSize: 30,
                        layout: 'fitColumns',
                        rowFormatter,
                    }}
                />
            </Box>
        </DefaultLayout>
    )
}
