// src/components/contest/CreateContest.vue
<template>
<div>
  <v-snackbar
      v-model="snackbar"
      :timeout="2000"
      :top="true"
    >
      {{snackbarText}}
    </v-snackbar>
    <v-container grid-list-md text-xs-center>
      <v-layout row wrap>
        <v-flex xs12>
          <v-text-field
            ref="contestName"
            v-model="contestName"
            :rules="[
              () => !!contestName || 'This field is required',
              () => contestName.length < 31 || '30 characters or less.'
            ]"
            label="Contest Name"
            required
            hint="At least 30 characters"
            counter="30"
          ></v-text-field>
        </v-flex>

        <v-flex xs12>
          <v-textarea
            v-model="description"
            auto-grow
            box
            label="Description (Optional)"
          ></v-textarea>
        </v-flex>

        <v-flex xs12>
          <v-text-field
            ref="password"
            v-model="password"
            label="Contest Password (Optional)"
          ></v-text-field>
        </v-flex>

        <v-flex xs12 lg6>
          <v-text-field
            v-model="startDateTime"
            label="Start DateTime"
            :rules="[
              () => !!startDateTime || 'This field is required',
              () => validateDateTime() || 'After than End DateTime.',
            ]"
            hint="YYYY/MM/DD HH:mm:ssZZ"
            required
          ></v-text-field>
        </v-flex>
        <v-flex xs12 lg6>
          <v-text-field
            v-model="endDateTime"
            label="End DateTime"
            :rules="[
              () => !!endDateTime || 'This field is required',
              () => validateDateTime() || 'Before than Start DateTime.',
              () => diffDateTime() || 'It is up to one month.',
            ]"
            hint="YYYY/MM/DD HH:mm:ssZZ"
            required
          ></v-text-field>
        </v-flex>
        <v-flex xs12>
          <v-text-field
            ref="addTargetSonghash"
            v-model="addTargetSonghash"
            label="Song Hash(sha256)"
            :error-messages="errorMessages"
          >
            <template v-slot:append-outer>
              <v-select
                v-model="selectLnMode"
                :items="lnmode"
                item-text="label"
                item-value="value"
                label="LNMODE"
                return-object
                solo
              ></v-select>
              <v-btn 
                icon
                ripple
                :loading="loading"
                :disabled="loading"
                @click="addSong()"
              >
                <v-icon color="lighten-1">playlist_add</v-icon>
              </v-btn>
            </template>
          </v-text-field>
        </v-flex>
        <v-flex xs12>
          <v-card>
            <v-card-text>
              <v-layout row wrap>
                <v-flex xs3>
                  <v-subheader>Keyword</v-subheader>
                </v-flex>
                <v-flex xs7>
                  <v-text-field
                      v-model="title"
                      :rules="[rules.required, rules.min]"
                      type="text"
                      name="input-10-1"
                      hint="At least 3 characters"
                  ></v-text-field>
                </v-flex>
                <v-flex xs2 class="text-xs-right">
                  <v-btn 
                    outline 
                    flat
                    color="primary" 
                    @click.native="getSongData()" 
                    :disabled="!validate()"
                    :loading="loading">
                    Search
                  </v-btn>
                </v-flex>
                <v-flex xs12>
                  <v-dialog v-model="progress" persistent max-width="290">
                    <v-card>
                      <v-card-text>
                        <v-progress-linear indeterminate></v-progress-linear>
                      </v-card-text>
                    </v-card>
                  </v-dialog>
                  <div ref="table" style="height: 200px;"></div>
                </v-flex>
              </v-layout>
            </v-card-text>
          </v-card>
        </v-flex>

        <v-flex xs12>
          <v-list two-line>
            <template v-for="(item, index) in items">
              <v-subheader
                v-if="item.header"
                :key="item.header"
              >
                {{ item.header }}
              </v-subheader>

              <v-list-tile
                v-else
                :key="item.songhash + '.' + item.lnmode"
                avatar
              >
                <v-list-tile-avatar>
                  <v-icon>audiotrack</v-icon>
                </v-list-tile-avatar>
                <v-list-tile-content>
                  <v-list-tile-title v-html="item.title"></v-list-tile-title>
                  <v-list-tile-sub-title>{{item.songhash}} - {{ lnmode[item.lnmode].label }}</v-list-tile-sub-title>
                </v-list-tile-content>
                <v-list-tile-action>
                  <v-btn
                    icon 
                    ripple
                    @click="removeSong(index)"
                  >
                    <v-icon color="grey lighten-1">clear</v-icon>
                  </v-btn>
                </v-list-tile-action>
              </v-list-tile>
            </template>
          </v-list>
        </v-flex>
        <v-flex xs12>
          <v-btn block color="success" :disabled="enableSubmitButton() || loading" @click="submit()">Create Contest</v-btn>
        </v-flex>
      </v-layout>
    </v-container>
  </div>
</template>

<script>
/* eslint-disable */
import AWS from "aws-sdk";
import moment from 'moment';
import jssha from "jssha";
import axios from "axios";
import Tabulator from "tabulator-tables";
import { AmplifyEventBus } from 'aws-amplify-vue';
import { Auth } from 'aws-amplify';
const decrypt = require("../../decrypt");

export default {
  name: "CreateContest",
  props: {
    signedIn: Boolean
  },
  watch: {
    signedIn: async function(newValue, oldValue) {
      this.signedIn = newValue;
    },
    tableData:{
      handler: function (newData) {
        this.table.replaceData(newData);
      },
      deep: true,
    },
    addTargetSonghash: function(newValue) {
      this.$nextTick(()=> {
        const selectedData = this.table.getSelectedData();
        if (selectedData.length && newValue != selectedData[0].sha256) {
          this.table.deselectRow()
        }
      })
    },
  },
  mounted: function() {
    const self = this;
    this.table = new Tabulator(this.$refs.table, {
      layout: "fitDataStretch",
      reactiveData:true,
      columns: [
        { formatter: "textarea", title: "Title", field: "title"},
        { formatter: "textarea", title: "Artist", field: "artist"},
        { formatter: "textarea", title: "sha256", field: "sha256" },
      ],
      rowClick:function(e, row){
        const rowData = row.getData();
        self.addTargetSonghash = rowData.sha256;
      },
      selectable:1,
    });
  },
  data() {
    return {
      snackbar: false,
      snackbarText: "",
      title: "",
      table: null,
      tableData: [],
      progress: false,
      loading: false,
      errorMessages: '',
      contestName: "",
      description: "",
      password: "",
      startDateTime: moment().format("YYYY/MM/DD HH:mm:ssZZ"),
      endDateTime: moment().add(1,"day").format("YYYY/MM/DD HH:mm:ssZZ"),
      addTargetSonghash: null,
      items: [
          { header: 'Songs' }
      ],
      lnmode: [
        { label: 'LN or Default', value: 0 },
        { label: 'CN', value: 1 },
        { label: 'HCN', value: 2 }
      ],
      selectLnMode: { label: 'LN or Default', value: 0 },
      rules: {
        required: value => !!value || "Required.",
        min: v => v.length >= 3 || "Min 3 characters."
      }
    };
  },
  methods: {
    validate: function() {
      return (
        this.rules.required(this.title) == true &&
        this.rules.min(this.title) == true
      );
    },
    getSongData: function() {
      const self = this;
      this.loading = true;
      axios.get(`https://jdfts1v0wmdeklb-bms.adb.us-ashburn-1.oraclecloudapps.com/ords/bmsquery/bms_text/de6bd8b08c60?text=${this.title}`,{
        headers: {
          'Content-Type': 'application/json;charset=UTF-8',
          'Access-Control-Allow-Origin': '*',
        }
      })
      .then((val) => {
        if (val.data) {
          self.tableData = val.data.items
        }
      }).catch((err) => {
        self.tableData = []
      }).finally(() => {
        self.loading = false
      });
    },
    getCurrentUser: async function(){
      try{
        const data = await Auth.currentAuthenticatedUser();
        const returnData = {
            AccessToken: data.signInUserSession.accessToken.jwtToken,
            RefreshToken: data.signInUserSession.refreshToken.token,
            UserId: data.signInUserSession.idToken.payload.sub
        };
        // eslint-disable-next-line
        console.log(returnData);
        return returnData;
      } catch(err){
        // eslint-disable-next-line
        console.log(err);
        return {};
      }
    },
    enableSubmitButton: function () {
      if(this.contestName.length > 30 || this.contestName.length < 1 || !this.startDateTime) {
        return true;
      }

      if(this.items.length < 2){
        return true;
      }

      if(!this.validateDateTime()){
        return true;
      }
      
      if(!this.diffDateTime()){
        return true;
      }

      return false;
    },
    validateDateTime: function(){
      if(!moment(this.startDateTime, "YYYY/MM/DD HH:mm:ssZZ").isValid() || !moment(this.endDateTime, "YYYY/MM/DD HH:mm:ssZZ").isValid()){
        return false;
      }
      const start = moment(this.startDateTime, "YYYY/MM/DD HH:mm:ssZZ");
      const end = this.endDateTime ? moment(this.endDateTime, "YYYY/MM/DD HH:mm:ssZZ") : null;
      if(end && (start.isAfter(end))){
        return false;
      }

      return true;
    },
    diffDateTime: function() {
      if(!this.startDateTime){
        return false;
      }
      const start = moment(this.startDateTime, "YYYY/MM/DD HH:mm:ssZZ");
      const end = this.endDateTime ? moment(this.endDateTime, "YYYY/MM/DD HH:mm:ssZZ") : null;
      if(end && end.diff(start, 'months') > 1){
        return false;
      }

      return true;
    },
    submit: async function() {
      this.loading = true;
      let userData = await this.getCurrentUser();
      let contestName = this.contestName;
      let description = this.description ? this.description : null;
      let password = null;
      if(this.password){
        let shaObj = new jssha('SHA-512', 'TEXT');
        shaObj.update(this.password);
        password = shaObj.getHash("HEX");
      }
      let startDateTime = moment(this.startDateTime, "YYYY/MM/DD HH:mm:ssZZ");
      let endDateTime = moment(this.endDateTime, "YYYY/MM/DD HH:mm:ssZZ");
      let songs = [];
      for(let item of this.items){
        if(!item.songhash){
          continue;
        }
        songs.push(item.songhash + "." + item.lnmode);
      }

      const ks = decrypt.get("create_contest").split(",");
      AWS.config.update({
        accessKeyId: ks[0],
        secretAccessKey: ks[1]
      });
      AWS.config.region = "us-east-1";
      let lambda = new AWS.Lambda();
      let params = {
        FunctionName: "create_contest",
        Payload: JSON.stringify({
          AccessToken: userData.AccessToken,
          RefreshToken: userData.RefreshToken,
          contestName: contestName,
          description: description ? description : null,
          password: password ? password : null,
          startDateTime: startDateTime,
          endDateTime: endDateTime,
          songs: songs,
        })
      };

      const self = this;
      lambda.invoke(params, function(err, data) {
        if(err){
          self.snackbarText = "Failed to create Contest.";
          self.snackbar = true;
        }
        let json = JSON.parse(data.Payload.toString());
        self.$router.push(`/viewer/contest/${json.contestId}`);
      });
    },
    addSong: function() {
      this.loading = true;
      const songhash = this.addTargetSonghash;
      const lnmode = this.selectLnMode.value;

      const songItem = this.items.find((element) => {
        return element.songhash && element.songhash == songhash && element.lnmode == lnmode;
      });

      if(songItem){
        this.loading = false;
        return;
      }

      const self = this;

      const ks = decrypt.get("get_song_data").split(",");
      AWS.config.update({
        accessKeyId: ks[0],
        secretAccessKey: ks[1]
      });
      AWS.config.region = "us-east-1";
      let lambda = new AWS.Lambda();
      let params = {
        FunctionName: "get_song_data",
        Payload: JSON.stringify({
          songhash: songhash + "." + lnmode
        })
      };

      lambda.invoke(params, function(err, data) {
        self.loading = false;
        if (!err) {
          const json = JSON.parse(data.Payload.toString());
          if(!json.message){
            self.errorMessages = "Song not found";
            return;
          } else if (json.message == "success") {
            json.SongData.lnmode = lnmode;
            self.items.push(json.SongData);
            self.addTargetSonghash = "";
          }
        }
      });
    },
    removeSong: function(index) {
      this.items.splice(index, 1);
    }
  }
};
</script>

// src/pages/contest/createContest.tsx
import {
    Box,
    Link,
    Table,
    TableContainer,
    Tbody,
    Td,
    Th,
    Thead,
    Tr,
    Heading,
    Progress,
    Text,
    Tag,
    Flex,
    Container,
    Input,
    Textarea,
    InputGroup,
    IconButton,
    InputRightElement,
    Select,
    useToast,
    SimpleGrid,
    Button,
    Badge,
    Spacer,
} from '@chakra-ui/react'
import Lambda from 'aws-sdk/clients/lambda'
import { getAccessKeyAndSecret } from '~/util/decrypt'
import AWS from 'aws-sdk'
import { useEffect, useRef, useState } from 'react'
import { Link as ReactLink, useNavigate } from 'react-router-dom'
import { DefaultLayout } from '~/layout/Default'
import { AddIcon, ArrowUpIcon, CopyIcon, DeleteIcon, ExternalLinkIcon, SearchIcon } from '@chakra-ui/icons'
import { Helmet } from 'react-helmet-async'
import axios from 'axios'
import dayjs from 'dayjs'
import utc from 'dayjs/plugin/utc'
import isBetween from 'dayjs/plugin/isBetween'
import isSameOrAfter from 'dayjs/plugin/isSameOrAfter'
import { Auth } from 'aws-amplify'
import jssha from 'jssha'
import DatePicker from 'react-datepicker'
import 'react-datepicker/dist/react-datepicker.css'
import { cloneDeep } from 'lodash'
dayjs.extend(utc)
dayjs.extend(isBetween)
dayjs.extend(isSameOrAfter)

type SongList = {
    title: string
    sha256: string
}

type SongData = {
    artist: string
    bpm: number
    datetime: string
    genre: string
    judgerank: number
    level: string
    maxbpm: number
    minbpm: number
    mode: string
    notes: number
    songhash: string
    title: string
    total: number
    lnmode?: number
    video?: {
        videoid: string
        updateUserId: string
    }
}

const LNMODE = [
    { label: 'LN or #LNMODE', value: 0 },
    { label: 'CN', value: 1 },
    { label: 'HCN', value: 2 },
]

export default () => {
    const navigate = useNavigate()
    const [tableData, setTableData] = useState<SongList[]>([])
    const [isLoading, setLoading] = useState(false)
    const [isSongLoading, setSongLoading] = useState(false)
    const [isSubmittedLoading, setSubmittedLoading] = useState(false)
    const toast = useToast()

    useEffect(() => {
        setTableData([])
    }, [])

    const getLatestData = async () => {
        const { data } = await axios.get(
            `https://jdfts1v0wmdeklb-bms.adb.us-ashburn-1.oraclecloudapps.com/ords/bmsquery/bms_text/de6bd8b08c60?text=${searchText}`,
            {
                headers: {
                    'Content-Type': 'application/json;charset=UTF-8',
                    'Access-Control-Allow-Origin': '*',
                },
            },
        )

        return data ? data.items : []
    }

    const search = (e: React.MouseEvent<HTMLButtonElement>) => {
        e.preventDefault()
        setLoading(true)
        !(async () => {
            try {
                const data = await getLatestData()
                setTableData(data)
                if (!data.length) {
                    toast({
                        description: 'No search result.',
                        status: 'info',
                        duration: 1500,
                    })
                }
            } catch (error) {
                toast({
                    description: 'Failed to search.',
                    status: 'error',
                    duration: 1500,
                })
            } finally {
                setLoading(false)
            }
        })()
    }

    const [contestName, setContestName] = useState<string>()
    const [description, setDescription] = useState<string>()
    const [password, setPassword] = useState<string>()
    const [startDateTime, setStartDateTime] = useState<Date>()
    const [endDateTime, setEndDateTime] = useState<Date>()
    const [items, setItems] = useState<SongData[]>([])
    const [searchText, setSearchText] = useState<string>()
    const [sha256, setSha256] = useState<string>()
    const [selectLnMode, setSelectLnMode] = useState<string>('0')

    const handleContestNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const inputValue = e.target.value
        setContestName(inputValue)
    }

    const handleDescriptionChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
        const inputValue = e.target.value
        setDescription(inputValue)
    }

    const handlePasswordChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const inputValue = e.target.value
        setPassword(inputValue)
    }

    const handleStartDateTimeChange = (date: Date) => {
        setStartDateTime(date)
    }

    const handleEndDateTimeChange = (date: Date) => {
        setEndDateTime(date)
    }

    const handleSearchTextChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const inputValue = e.target.value
        setSearchText(inputValue)
    }

    const handleSha256Change = (e: React.ChangeEvent<HTMLInputElement>) => {
        const inputValue = e.target.value
        setSha256(inputValue)
    }

    const handleSelectLnModeChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
        const inputValue = e.target.value
        setSelectLnMode(inputValue)
    }

    const addSong = async () => {
        setSongLoading(true)
        const songhash = sha256
        const lnmode = Number(selectLnMode)

        const songItem = items.find((element) => {
            return element.songhash && element.songhash == songhash && element.lnmode == lnmode
        })

        if (songItem) {
            setSongLoading(false)
            return
        }

        const ks = getAccessKeyAndSecret('get_song_data').split(',')
        AWS.config.update({
            accessKeyId: ks[0],
            secretAccessKey: ks[1],
        })
        const lambda = new AWS.Lambda()
        const params = {
            FunctionName: 'get_song_data',
            Payload: JSON.stringify({
                songhash: songhash + '.' + selectLnMode,
            }),
        }
        try {
            const data = await lambda.invoke(params).promise()
            const json = JSON.parse(data.Payload?.toString() ?? '')

            if (!json.message) {
                throw new Error('Song not found')
            }

            json.SongData.lnmode = lnmode
            const _items = cloneDeep(items)
            _items.push(json.SongData)
            setItems(_items)
            setSha256('')
        } catch (e) {
            console.error(e)
            toast({
                description: 'Failed to create contest.',
                status: 'error',
                duration: 1500,
            })
        } finally {
            setSongLoading(false)
        }
    }

    const removeSong = (index: number) => {
        const _items = cloneDeep(items)
        _items.splice(index, 1)
        setItems(_items)
    }

    const submit = async () => {
        setSubmittedLoading(true)

        const data = await Auth.currentAuthenticatedUser()
        const userData = {
            AccessToken: data.signInUserSession.accessToken.jwtToken,
            RefreshToken: data.signInUserSession.refreshToken.token,
            UserId: data.signInUserSession.idToken.payload.sub,
        }

        let _password = password
        if (!!_password) {
            const shaObj = new jssha('SHA-512', 'TEXT')
            shaObj.update(_password)
            _password = shaObj.getHash('HEX')
        }

        const _startDateTime = dayjs(startDateTime, 'YYYY/MM/DD HH:mm:ssZZ')
        const _endDateTime = dayjs(endDateTime, 'YYYY/MM/DD HH:mm:ssZZ')
        const songs = []
        for (let item of items) {
            if (!item.songhash) {
                continue
            }
            songs.push(item.songhash + '.' + item.lnmode)
        }

        const ks = getAccessKeyAndSecret('create_contest').split(',')
        AWS.config.update({
            accessKeyId: ks[0],
            secretAccessKey: ks[1],
        })
        const lambda = new AWS.Lambda()
        const params = {
            FunctionName: 'create_contest',
            Payload: JSON.stringify({
                AccessToken: userData.AccessToken,
                RefreshToken: userData.RefreshToken,
                contestName: contestName,
                description: description ? description : null,
                password: _password ? _password : null,
                startDateTime: _startDateTime,
                endDateTime: _endDateTime,
                songs: songs,
            }),
        }
        try {
            const data = await lambda.invoke(params).promise()
            const json = JSON.parse(data.Payload?.toString() ?? '')
            navigate(`/viewer/contest/${json.contestId}`)
        } catch (e) {
            console.error(e)
            toast({
                description: 'Failed to create contest.',
                status: 'error',
                duration: 1500,
            })
        } finally {
            setSubmittedLoading(false)
        }
    }

    return (
        <DefaultLayout>
            <Helmet>
                <title>Create Contest</title>
            </Helmet>
            <Box padding={4}>
                <Flex flexDirection={'column'}>
                    <Box m={1}>
                        <Input placeholder="Contest name" value={contestName} onChange={handleContestNameChange}></Input>
                    </Box>
                    <Box m={1}>
                        <Textarea
                            placeholder="Description (Optional)"
                            value={description}
                            onChange={handleDescriptionChange}></Textarea>
                    </Box>
                    <Box m={1}>
                        <Input placeholder="Contest password (Optional)" value={password} onChange={handlePasswordChange}></Input>
                    </Box>
                    <SimpleGrid m={1} columns={{ base: 1, md: 2 }} spacing={2}>
                        <Box>
                            <Input
                                as={DatePicker}
                                selected={startDateTime}
                                /*
                                // @ts-ignore */
                                onChange={handleStartDateTimeChange}
                                showTimeSelect
                                dateFormat="Pp"
                                isClearable
                                placeholderText="Start Datetime (Optional)"
                            />
                        </Box>
                        <Box>
                            <Input
                                as={DatePicker}
                                selected={endDateTime}
                                /*
                                // @ts-ignore */
                                onChange={handleEndDateTimeChange}
                                showTimeSelect
                                dateFormat="Pp"
                                isClearable
                                placeholderText="End Datetime (Optional)"
                            />
                        </Box>
                    </SimpleGrid>
                    <Box m={1}>
                        <InputGroup variant={'outline'}>
                            <Input pr="11rem" placeholder={'sha256'} value={sha256} onChange={handleSha256Change} />
                            <InputRightElement width="11rem">
                                <Select value={selectLnMode} size={'xs'} mr={2} onChange={handleSelectLnModeChange}>
                                    {LNMODE.map((l) => (
                                        <option value={l.value}>{l.label}</option>
                                    ))}
                                </Select>
                                <IconButton aria-label="Add song" icon={<AddIcon />} size={'xs'} mr={2} onClick={addSong} />
                            </InputRightElement>
                        </InputGroup>
                    </Box>
                    <Box m={1} shadow={'md'}>
                        {isSongLoading && <Progress size="xs" isIndeterminate />}
                        {items.map((i, index) => (
                            <Flex m={2} borderWidth={1} rounded={'md'}>
                                <Badge>{index + 1}</Badge>
                                <Box>
                                    <Text fontWeight="bold">{i.title}</Text>
                                    <Text fontSize="sm">{LNMODE[i.lnmode!].label}</Text>
                                </Box>
                                <Spacer />
                                <IconButton
                                    aria-label="Remove song"
                                    icon={<DeleteIcon />}
                                    size={'xs'}
                                    mt={'auto'}
                                    colorScheme={'red'}
                                    isLoading={isSongLoading}
                                    onClick={() => removeSong(index)}
                                />
                            </Flex>
                        ))}
                    </Box>
                    <Box m={1}>
                        <Button
                            w={'full'}
                            disabled={!contestName || !items.length}
                            isLoading={isSubmittedLoading}
                            colorScheme={'teal'}
                            onClick={() => submit()}>
                            CREATE CONTEST
                        </Button>
                    </Box>
                    <Box m={1} shadow={'md'}>
                        <Flex p={4} alignItems={'center'} flexDirection={'column'}>
                            <InputGroup size="md" width={{ base: '100%' }}>
                                <Input
                                    value={searchText}
                                    placeholder={'Search text (Need 3 characters)'}
                                    variant="outline"
                                    pr="4.5rem"
                                    onChange={handleSearchTextChange}
                                />
                                <InputRightElement width="4.5rem">
                                    <IconButton
                                        aria-label="search"
                                        icon={<SearchIcon />}
                                        size={'sm'}
                                        onClick={search}
                                        disabled={!searchText || searchText.length < 3}
                                        isLoading={isLoading}
                                    />
                                </InputRightElement>
                            </InputGroup>
                        </Flex>
                        {isLoading && <Progress size="xs" isIndeterminate />}
                        <TableContainer>
                            <Table variant="striped" size="sm">
                                <Thead>
                                    <Tr>
                                        <Th>TITLE</Th>
                                        <Th display={{ base: 'none', md: 'table-cell' }}>SHA256</Th>
                                    </Tr>
                                </Thead>
                                <Tbody>
                                    {tableData.map((d, index) => (
                                        <Tr key={index}>
                                            <Td>
                                                <Text isTruncated>{d.title}</Text>
                                            </Td>
                                            <Td display={{ base: 'none', md: 'table-cell' }}>
                                                <Text>{d.sha256}</Text>
                                            </Td>
                                            <Td>
                                                <Button
                                                    rightIcon={<ArrowUpIcon />}
                                                    colorScheme="teal"
                                                    variant="outline"
                                                    size={'xs'}
                                                    onClick={() => setSha256(d.sha256)}>
                                                    Set to SHA256 field
                                                </Button>
                                            </Td>
                                        </Tr>
                                    ))}
                                </Tbody>
                            </Table>
                        </TableContainer>
                    </Box>
                </Flex>
            </Box>
        </DefaultLayout>
    )
}
