// src/pages/latest.tsx
import { Box, Link, Table, TableContainer, Tbody, Td, Th, Thead, Tr, Heading, Progress, Text } from '@chakra-ui/react'
import { useParams } from 'react-router-dom'
import Lambda from 'aws-sdk/clients/lambda'
import { getAccessKeyAndSecret } from '~/util/decrypt'
import AWS from 'aws-sdk'
import { useEffect, useState } from 'react'
import { Link as ReactLink } from 'react-router-dom'
import { DefaultLayout } from '~/layout/Default'
import { ExternalLinkIcon } from '@chakra-ui/icons'
import { Helmet } from 'react-helmet-async'

type SongList = {
    title: string
    artist: string
    songhash: string
}

export default () => {
    const urlParams = useParams<{ key: string }>()
    const [tableData, setTableData] = useState<SongList[]>([])
    const [isLoading, setLoading] = useState(false)

    useEffect(() => {
        setLoading(true)
        setTableData([])
        getLatestData()
    }, [urlParams.key])

    const getLatestData = () => {
        const ks = getAccessKeyAndSecret('get_played_100').split(',')
        AWS.config.update({
            accessKeyId: ks[0],
            secretAccessKey: ks[1],
        })
        const lambda = new Lambda()
        const params = {
            FunctionName: 'get_played_100',
            Payload: JSON.stringify({
                mode: urlParams.key ?? 'beat-7k',
            }),
        }

        lambda.invoke(params, function (err, data) {
            if (err) {
            } else {
                var json = JSON.parse(data.Payload?.toString() ?? '')
                if (json.message == 'success') {
                    setTableData(json.songDatas)
                } else {
                }
            }
            setLoading(false)
        })
    }

    return (
        <DefaultLayout>
            <Helmet>
                <title>{urlParams.key} Latest 100 played</title>
            </Helmet>
            <Box padding={4}>
                <Heading marginBottom={4}>{urlParams.key} Latest 100 played</Heading>
                {isLoading && <Progress size="xs" isIndeterminate />}
                <TableContainer>
                    <Table variant="striped" size="sm">
                        <Thead>
                            <Tr>
                                <Th w={'32px'}>IR</Th>
                                <Th maxW={'95vw'}>TITLE</Th>
                            </Tr>
                        </Thead>
                        <Tbody>
                            {tableData.map((d, index) => (
                                <Tr key={index}>
                                    <Td>
                                        <Link as={ReactLink} to={`/viewer/song/${d.songhash}/0`}>
                                            <ExternalLinkIcon />
                                        </Link>
                                    </Td>
                                    <Td maxW={'95vw'}>
                                        <Text isTruncated>{d.title}</Text>
                                    </Td>
                                </Tr>
                            ))}
                        </Tbody>
                    </Table>
                </TableContainer>
            </Box>
        </DefaultLayout>
    )
}

// src/components/Latest.vue
<template>
  <v-container text-xs-center>
      <v-layout align-space-between justify-center row fill-height v-resize="onResize">
        <v-flex xs12>
          <v-dialog v-model="progress" persistent max-width="290">
            <v-card>
              <v-card-text>
                <v-progress-linear indeterminate></v-progress-linear>
              </v-card-text>
            </v-card>
          </v-dialog>
          <div ref="table"></div>
        </v-flex>
      </v-layout>
    </v-container>
</template>

<script>
/* eslint-disable */
import AWS from "aws-sdk";
import Tabulator from "tabulator-tables";
const decrypt = require("../decrypt");

export default {
  name: "Latest",
  watch: {
    '$route' (to, from) {
      this.getLatestData();
    },
    tableData:{
      handler: function (newData) {
        this.table.replaceData(newData);
      },
      deep: true,
    }
  },
  props: {
    msg: String
  },
  mounted: function() {
    this.table = new Tabulator(this.$refs.table, {
      layout: "fitColumns",
      height: this.tableHeight(),
      reactiveData:true,
      columns: [
        { formatter: "rownum", align: "center", width: 40, headerSort: false, resizable: false },
        { formatter: "textarea", title: "Title", field: "title", minWidth: 200, headerSort: false, resizable: false },
        { formatter: "textarea", title: "Artist", field: "artist", minWidth: 200, headerSort: false, resizable: false },
        {
          title: "IR Links",
          field: "songhash",
          width: 80,
          formatter: function(cell, formatterParams) {
            let value = cell.getValue();
            return `<a href="./#/viewer/song/${value}/0">IR</a><br><a href="./#/viewer/song/${value}/1">IR(CN)</a><br><a href="./#/viewer/song/${value}/2">IR(HCN)</a>`;
          },
          headerSort: false, 
          resizable: false
        }
      ]
    });

    this.getLatestData();
  },
  data() {
    return {
      table: null,
      progress: false,
      tableData: []
    };
  },
  methods: {
    onResize () {
      if(this.table){
        this.table.setHeight(this.tableHeight());
        this.table.redraw();
      }
    },
    tableHeight: function () {
      return window.innerHeight -100 + "px";
    },
    getMode: function(){
      return this.$route.params.mode;
    },
    getLatestData: function() {
      this.progress = true;
      let mode = this.getMode();
      const self = this;
      this.tableData = [];

      const ks = decrypt.get("get_played_100").split(",");
      AWS.config.update({
        accessKeyId: ks[0],
        secretAccessKey: ks[1]
      });
      AWS.config.region = "us-east-1";
      var lambda = new AWS.Lambda();
      var params = {
        FunctionName: "get_played_100",
        Payload: JSON.stringify({
          mode: mode ? mode : "beat-7k"
        })
      };

      lambda.invoke(params, function(err, data) {
        self.progress = false;
        if (err) {
        } else {
          var json = JSON.parse(data.Payload.toString());
          if (json.message == "success") {
            self.tableData = json.songDatas;
          } else {
          }
        }
      });
    }
  }
};
</script>

<style>
  @import '~tabulator-tables/dist/css/tabulator.min.css';
</style>
